- name: Install Nginx
  hosts: all
  tasks:
  - name: update packages and install nginx
    apt:
      update_cache: yes
      name: nginx
      state: latest
    register: output
    until: output.stderr == ""
    retries: 10
    
  - name: enable nginx
    systemd:
      name: nginx
      enabled: yes
      state: started